version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./pg-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    env_file:
      - .prod-env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_NAME}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 6
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL
             gunicorn mealprep.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/mealprep/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/mealprep/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
