# Generated by Django 4.1.2 on 2022-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractiverecipe',
            name='n_portions',
        ),
        migrations.AddField(
            model_name='usershoppinglist',
            name='quantity_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usershoppinglist',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
