# Generated by Django 4.1.2 on 2022-12-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_useractiverecipe_n_portions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoppinglist',
            name='quantity_str',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
