# Generated by Django 4.1.4 on 2022-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_usershoppinglist_quantity_str'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useractiverecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe'),
        ),
    ]
