# Generated by Django 4.1.4 on 2022-12-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_useractiverecipe_unique_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useractiverecipe',
            name='unique_recipe',
        ),
    ]
